include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    prefer_double_quotes: true # Prefer double quotes
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    await_only_futures: true