name: dice_tower
description: A flutter package for rolling dice using the rules for various table top games.
version: 0.6.5
homepage: https://github.com/martin-labanic/dice_tower

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
#  plugin:
#    platforms:
#      android:
#        package:
#        pluginClass:
#      ios:
#        pluginClass: